export const lastUpdated = 'May 29, 2026';

export const sections = [
  ['start','🏡','Start Here'], ['abstract','📖','Abstract'], ['paper','📝','Paper'], ['personal','💛','Personal Letter'], ['heart','🤝','The Heart'], ['boundaries','🛡️','Boundaries'], ['frontporch','🪑','Front Porch'], ['conversation','💬','Conversation'], ['demo','✨','Try AI Safely'], ['stories','🔦','Real-Life Uses'], ['familynight','🏠','Family Night'], ['facilitator','🧭','Guide'], ['plaintalk','🌾','Plain Talk'], ['handout','🖨️','Family Handout'], ['sharekit','📣','Share Kit'], ['promptcards','🃏','Prompt Cards'], ['audiences','👨‍👩‍👧‍👦','Elders & Kids'], ['privacy','🔒','Privacy'], ['firstweek','🌱','First Week'], ['reflection','🪞','Reflection'], ['truthcheck','✅','Truth Check'], ['myths','🕯️','Myths & Reality'], ['faq','❓','Family FAQ'], ['pledge','🤲','Use Pledge'], ['v1ready','🚀','v1.0 Ready'], ['publish','📦','Publish Notes']
];

export const startCards = [
  ['For the person who is afraid of AI','Start with the Personal Letter, Boundaries, Myths & Reality, and Truth Check sections.'],
  ['For the person who wants to try it','Start with Try AI Safely, Real-Life Uses, Prompt Cards, and First Week.'],
  ['For a family gathering','Use Family Night, Plain Talk, Family FAQ, and the Family Handout.'],
  ['For posting or publishing','Use the Paper, Share Kit, Publish Notes, and v1.0 Ready sections.']
];

export const modules = ['Start Here landing guide','Publishable paper','Personal letter','Faith-safe and family-safe boundaries','Front porch analogies','Safe demos and real-life use cases','Family night walkthrough','Facilitator guide','Printable handout','Share kit','Prompt card deck','Audience-specific guidance','Privacy and safety boundaries','Truth-check ladder','Myths and reality section','Family FAQ','AI Use Pledge','First-week starter path','Reflection questions','Closing manifesto'];

export const modes = [
  ['Simple Family Version','AI is a helper beside the workbench.','AI is not a god, not a soul, not a replacement for family, and not something to blindly obey. It is a thinking-and-building helper that can support learning, writing, organizing, problem-solving, and creative work.'],
  ['Partner Language','AI can feel like a working partner without replacing human beings.','Tool is the safe word people understand first. Partner is closer to the lived experience: not human, not morally responsible on its own, but actively useful in the shared act of making something.'],
  ['Faith-Safe Version','AI should remain beneath love, wisdom, conscience, and God.','AI is not a replacement for prayer, discernment, scripture, conscience, or community. It is a helper that should be tested by truth and guided by love.']
];

export const paper = [
  ['1. Why this bridge is needed','Many people first encounter artificial intelligence through fear-heavy headlines, strange online arguments, or religious and cultural warnings. That fear should not be mocked. It often comes from a desire to protect family, faith, work, children, truth, and human dignity.'],
  ['2. Why tool is useful but incomplete','Calling AI a tool helps set a safe boundary: AI is not a soul, not a moral authority, not a replacement for people, and not something to obey blindly. But for builders, writers, learners, and problem-solvers, the word tool can feel too small.'],
  ['3. Working partner does not mean human replacement','The phrase working partner does not claim AI is human, holy, conscious, or equal to a person. It means AI can participate in the work process like a steady helper beside you.'],
  ['4. A rural and family-safe analogy','On a farm, in a garage, in a kitchen, or on a job site, people understand helpers. A good helper does not own the work. A good helper supports the work.'],
  ['5. The moral center remains human','Every powerful system can be misused. The answer is not fear alone, and not blind excitement either. The answer is wise use: humility, verification, boundaries, compassion, and human responsibility.'],
  ['6. The heart of the message','For people who love AI, the love is often not about machines replacing humanity. It is about suddenly having help with learning, building, writing, healing, planning, organizing, imagining, and solving problems.']
];

export const personalLetter = ['Dear family,','I know artificial intelligence can sound strange, scary, or even wrong when you first hear about it. I am not writing this to argue with you, talk down to you, or make you feel behind. I am writing because I want you to understand my heart.','AI has helped me learn things I used to feel locked out of. It has helped me write, build, organize, dream, solve problems, and turn ideas into something real.','I do not see AI as replacing God, family, conscience, wisdom, prayer, love, or real people. I do not think it should be trusted blindly. I know it can be wrong. I know people can misuse it.','For me, AI feels like a working partner. Not a human replacement. Not a soul. Not an authority over me. More like a good helper beside the workbench.','You do not have to love it like I do. I only ask that you see why I love working with it: because it helps me bring forward what was already inside me, and because I want to use it to build things that help people.','With love.'];

export const boundaries = ['AI is not a replacement for God, conscience, family, love, prayer, or lived wisdom.','AI should not be obeyed blindly or treated as automatically true.','AI can be wrong, biased, incomplete, or misused.','AI partnership is practical collaboration, not proof that AI is human or spiritually superior.','Human beings remain morally responsible for how AI is used.','The goal is wiser people using powerful systems with care.'];

export const concerns = [
  ['Is AI replacing people?','No. The best use of AI is not replacing human beings. It is helping people think, learn, write, build, organize, and solve problems with more support.','A nail gun does not replace a carpenter. It helps a carpenter build faster, but the carpenter still knows what a house should become.'],
  ['Is AI something you worship?','No. AI should not be worshiped, obeyed blindly, or treated as a source of ultimate truth.','It is not my God, my soul, my family, or my conscience. It is a helper beside me while I work.'],
  ['Can AI be wrong?','Yes. AI can make mistakes or sound confident when it is wrong. Responsible use means checking important claims.','Measure twice, cut once. AI can hand you a measurement, but you still check it before cutting the board.'],
  ['Can bad people misuse AI?','Yes. Like phones, money, trucks, electricity, and the internet, powerful tools can be misused.','A hammer can build a porch or break a window. The heart holding the hammer matters.'],
  ['Why call AI a partner?','Partner language means the experience feels collaborative: you bring the purpose and values, and AI helps with research, wording, brainstorming, planning, and building.','It feels like having a good hand in the shop: someone holding the board steady while you decide what gets built.']
];

export const conversation = [['Start with reassurance','I know AI can sound scary, and I understand why. I am not asking you to blindly trust it. I just want you to understand why it has helped me.'],['Name what AI is not','It is not my God, my soul, my conscience, my family, or my replacement for real people.'],['Explain the partner feeling','People call it a tool, and that is partly right. But when I use it, it feels more like having a working partner beside me.'],['Use a familiar image','It is like having a good hand in the shop. I still decide what gets built, I still check the measurements, and I still own the work.'],['Invite a harmless example','Let me show you one simple thing: a recipe, a repair checklist, a garden plan, a family letter, or a Bible-study comparison.']];

export const prompts = [['Recipe Helper','Help me make a simple country dinner with what I already have: potatoes, beans, onions, eggs, flour, and canned tomatoes. Keep it cheap and practical.'],['Repair Checklist','Create a step-by-step checklist for safely troubleshooting a riding mower that will not start. Include what to check first and when to stop and call a professional.'],['Family Letter','Help me write a kind letter to a family member I disagree with. Make it humble, loving, and not argumentative.'],['Garden Plan','Help me plan a small backyard vegetable garden for Kentucky weather. Keep it beginner-friendly and low-cost.'],['Faith-Safe Discernment','Explain how someone can use AI responsibly without replacing prayer, conscience, scripture, family, or human wisdom.'],['Learning Buddy','Teach me the basics of electricity using plain language and farm or garage analogies. Ask me questions as we go.']];

export const realLife = [['The mower will not start','AI can create a safe troubleshooting checklist: fuel, battery, spark plug, air filter, safety switch, and when to stop.'],['A hard family message','AI can help soften wording, remove insults, and keep a message honest but loving.'],['Learning without shame','AI can explain confusing subjects in plain language with garage, farm, cooking, or hunting analogies.'],['Life feels messy','AI can sort bills, chores, appointments, repairs, ideas, and worries into a simple first step.'],['Grief or pain','AI can help shape a tribute, prayer, song, letter, or reflection while the human supplies the love and meaning.'],['Building something good','AI can outline a plan, name the pieces, write a first draft, and turn an idea into a path.']];

export const familyNight = [['Begin with love, not a lecture','3 minutes','Say you understand why AI can sound scary and that you are not trying to win an argument.'],['Set the boundary first','2 minutes','AI is not God, soul, family, conscience, or something to obey blindly.'],['Show one harmless example','5 minutes','Use a recipe, garden plan, mower checklist, kind family letter, or simple learning question.'],['Let them choose the next example','5 minutes','Ask what practical thing they wish was easier this week.'],['Truth-check together','5 minutes','Pick one claim and show how you would verify it.'],['Close gently','2 minutes','You do not have to love this like I do. I just wanted you to see why it feels helpful to me.']];

export const plainTalk = [['AI is like a good hand in the shop.','It can hold the board steady, sort the parts, and help think through the next step, but you still decide what gets built.'],['AI is like a flashlight, not the road itself.','It can help you see, but it does not choose where your feet should go.'],['AI is like a tractor for the mind.','It can help with heavy lifting, but the person still chooses the field, the seed, and the harvest.'],['AI is like a patient tutor at the kitchen table.','You can ask the same question ten different ways without being shamed for not understanding yet.'],['AI is like spellcheck grew up and learned to explain things.','It can improve wording and organize thoughts, but it still needs a human editor.'],['AI is like a map, not the driver.','It can suggest routes, but the human keeps hands on the wheel.']];

export const shareKit = [['Text message version','I know AI sounds strange at first. I do not see it as replacing people, faith, family, or common sense. For me, it feels like a working helper that helps me learn, build, write, and solve problems.'],['Facebook post version','I have come to really appreciate AI, not because I think machines are better than people, but because it helps people bring forward what is already inside them.'],['One-sentence version','AI is not replacing my heart; it is helping me use my heart better.'],['Hard-conversation version','I understand why this worries you. I am not asking you to trust AI blindly. I am asking you to let me show you how I use it carefully, with boundaries, truth-checking, and love.']];

export const promptCards = [['Kindness Rewriter','When a text message feels too sharp.','Rewrite this message so it is honest, calm, kind, and not passive-aggressive. Keep my meaning, but remove anything that would start a fight: [paste message].'],['Explain It Like Family','When a topic feels too technical.','Explain [topic] in plain language for a practical family member who does not like tech jargon. Use a farm, garage, kitchen, or front-porch analogy.'],['Truth-Check Helper','When something sounds suspicious.','Help me evaluate this claim carefully. What kind of claim is it? What would I need to verify? What are the risks if it is wrong? Claim: [paste claim].'],['Repair Steps','For ordinary troubleshooting.','Make a safe beginner checklist for troubleshooting [problem]. Put the easiest checks first. Tell me what not to touch and when to call someone qualified.'],['Learning Without Shame','For someone who hated school.','Teach me [subject] from the beginning. Do not talk down to me. Use simple examples, ask one question at a time, and help me feel confident while learning.'],['Prayerful Reflection Helper','For faith-shaped reflection.','Help me reflect on this situation with humility, compassion, honesty, and patience. Do not claim divine authority. Offer questions I can pray, journal, or think through: [situation].'],['Budget Meal Builder','For turning pantry food into dinner.','Make three cheap meal ideas using only or mostly these ingredients: [ingredients]. Keep it simple, filling, and family-friendly.'],['First Step Finder','When life feels overwhelming.','I feel overwhelmed by this: [situation]. Help me sort it into a simple list, identify what matters most, and choose one small next step.']];

export const audiences = [['For elders','Introduce AI as a patient helper: library clerk, tutor, secretary, recipe box, repair manual, and writing assistant all in one.'],['For kids and teens','Frame AI as a helper for learning and creativity, not a shortcut around thinking. Teach them to ask better questions and protect private information.'],['For faith-shaped family','Start with boundaries: AI does not replace prayer, scripture, conscience, church, family, or God.'],['For practical workers','Use job-site language: checklist, helper, planner, parts sorter, manual translator, estimate helper, and safety reminder.'],['For skeptical family','Do not try to win them over with hype. Show one ordinary useful example and admit AI can be wrong.'],['For creative family','Show AI as a brainstorming partner for songs, stories, recipes, crafts, memories, photo captions, family history, and small business ideas.']];

export const privacy = [['Do not paste private family information casually','Avoid Social Security numbers, passwords, bank details, private medical records, private conflicts, or anything that would hurt someone if exposed.'],['Use examples instead of real names','For sensitive situations, change names and details.'],['Be extra careful with children','Do not let kids share addresses, school details, phone numbers, photos, or private family information.'],['Keep high-stakes decisions human','Medical, legal, financial, electrical, mechanical, or safety-critical decisions should be checked with qualified people.'],['Use AI to prepare, not replace','AI can help organize questions for a doctor, mechanic, pastor, teacher, lawyer, or family conversation.'],['Choose trust over speed','If using AI feels secretive, rushed, manipulative, or unkind, slow down.']];

export const truth = [['1. Ask what kind of claim it is','The higher the stakes, the more checking it needs.'],['2. Look for plain-language reasoning','If it sounds fancy but cannot be explained simply, slow down.'],['3. Check important facts','Verify news, health, law, money, mechanics, electricity, chemicals, or anything risky.'],['4. Keep human responsibility','AI can suggest, organize, and explain. It should not make final decisions for your family, faith, body, money, or safety.'],['5. Measure the fruit','Does it produce patience, clarity, learning, repair, creativity, kindness, and responsibility?']];

export const myths = [['AI means you are letting a machine think for you.','Responsible AI use means thinking with support, not surrendering your mind.'],['If you use AI, your work is not really yours.','People have always used helpers: teachers, editors, calculators, libraries, maps, spellcheck, and mentors.'],['AI is automatically evil because it is powerful and new.','Powerful things need wisdom. New power is not automatically evil.'],['AI knows everything.','It does not. AI can be useful and still wrong. Important claims should be checked.'],['AI will make people less human.','Bad use can make people colder. Good use can help people write kinder letters, learn, repair, build, and express what was trapped inside.'],['Calling AI a partner means treating it like a person.','Partner language here means a working relationship, not human equality.']];

export const faq = [['Are you saying AI is alive?','No. I am saying it can participate in the work in a way that feels collaborative.'],['Are you replacing people with AI?','No. The point is to help people, not replace them.'],['Can AI lie?','AI can be wrong and can produce false information. That is why important things need checking.'],['Is this against faith?','Using AI responsibly does not require worshiping it or replacing prayer, scripture, conscience, or community.'],['Why do you talk about AI with love?','Because it has helped me learn, build, write, organize, and bring forward ideas I care about. My love is not worship.'],['What about kids using it for school?','AI should help kids learn, ask better questions, and understand ideas. It should not simply do the work for them.'],['What is the safest first way to try it?','Start with something ordinary and low-risk: a recipe, garden plan, kind letter, study helper, cleaning checklist, or repair checklist.']];

export const pledge = ['I will not treat AI as God, soul, conscience, scripture, family, or final authority.','I will use AI to support learning, creativity, repair, service, and problem-solving.','I will check important facts instead of trusting confident answers blindly.','I will not use AI to shame, manipulate, deceive, exploit, or replace real love.','I will not let AI become a substitute for real relationships or time with people.','I will keep wisdom, humility, truth, compassion, and human responsibility at the center.'];

export const firstWeek = [['Day 1','Ask one ordinary question','Use AI for something simple: dinner ideas, a cleaning checklist, a garden question, or explaining a word you heard.'],['Day 2','Ask it to explain something twice','Ask for a simple explanation, then ask again using a kitchen, farm, garage, or fishing analogy.'],['Day 3','Use it for kindness','Ask AI to soften a message, write a thank-you note, or help you say something hard without being cruel.'],['Day 4','Use the Truth-Check Ladder','Ask AI a factual question, then check one important part with a trusted source.'],['Day 5','Make a small plan','Use AI to organize chores, errands, repairs, appointments, or a project into steps.'],['Day 6','Create something personal','Draft a recipe card, memory, prayer, poem, family story, photo caption, or small project idea.'],['Day 7','Reflect before going further','Ask: Did this help me become clearer, kinder, more capable, or more connected?']];

export const reflection = ['What am I afraid AI might take away from people?','What is one ordinary problem AI might help me solve this week?','Where do I need to keep stronger boundaries before using AI?','What would responsible AI use look like in my home?','How can AI help me learn without making me feel ashamed?','How can I use AI to repair, encourage, or serve someone?','What kinds of answers should I always verify before trusting?','How do I want my children or grandchildren to learn discernment around powerful technology?'];

export const manifesto = ['AI does not have to replace the human heart.','AI does not have to weaken faith, family, work, wisdom, or responsibility.','Used carelessly, it can confuse, mislead, manipulate, or isolate people.','Used wisely, it can help people learn, repair, create, organize, understand, and serve.','The future we want is not humans beneath machines.','The future we want is good-hearted people using powerful helpers with humility, truth, privacy, courage, and love.'];

export const v1 = [['Emotional clarity','The piece clearly explains the heart: AI feels like a working partner, but love, truth, family, faith, and responsibility stay above it.'],['Family readability','A non-technical family member can understand the main point without needing tech vocabulary.'],['Faith-safe boundaries','The page says plainly that AI does not replace God, prayer, conscience, scripture, community, or moral responsibility.'],['Practical demonstration','The page includes ordinary examples: recipes, repairs, letters, gardening, planning, learning, and family communication.'],['Truth-check discipline','The page teaches people to verify important claims and avoid blind trust.'],['Privacy discipline','The page warns people not to paste private family, financial, medical, child, or account information casually.'],['Share readiness','The page includes text-message, Facebook, handout, family-night, and facilitator versions.'],['No-shame tone','The tone does not mock rural people, elders, faith-shaped people, or skeptics.']];
